name: Docker

on:
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: Keycloak version
        required: true

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: version
        name: Get latest version
        run: |
          tag=$(git describe --abbrev=0 --tags)
          echo version=${tag:1:} >> $GITHUB_OUTPUTS

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            keycloak_version=${{ github.event.inputs.keycloak_version }}
          context: .
          push: true
          tags: gleroy/keycloak-bcrypt:${{ github.event.inputs.keycloak_version }}_${{ steps.version.outputs.version }},gleroy/keycloak-bcrypt:latest
